--require('neo-tree').setup({
--    window = {
--        mappings = {
--            ['e'] = function() vim.api.nvim_exec('Neotree focus filesystem left', true) end,
--            ['b'] = function() vim.api.nvim_exec('Neotree focus buffers left', true) end,
--            ['g'] = function() vim.api.nvim_exec('Neotree focus git_status left', true) end,
--        },
--        keys = {
--            {
--                "<leader>r",
--                function()
--                    require("neo-tree.command").execute({
--                        toggle = true,
--                        source = "buffers",
--                        position = "left",
--                    })
--                end,
--                desc = "Buffers (root dir)",
--            }
--        }
--    }
--})
